apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    isDefault: true
    url: $POSTGRES_HOST:$POSTGRES_PORT
    database: $POSTGRES_DB
    user: $POSTGRES_USER
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      sslmode: "disable"
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1000
      timescaledb: false
